; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
  ; --- SERVOMOTORES (Puertas, Pluma y Discoteca) ---
  madhephaestus/ESP32Servo @ ^1.1.1
  
  ; --- MOTOR A PASOS NEMA 17 (Elevador) ---
  waspinator/AccelStepper @ ^1.64
  
  ; --- NEOPIXEL (Discoteca) ---
  adafruit/Adafruit NeoPixel @ ^1.11.0
  
  ; --- SENSOR DE TEMPERATURA/HUMEDAD (AHT10/AHT20) ---
  adafruit/Adafruit AHTX0 @ ^2.0.5